[window]
padding = {x = 8, y = 8}
title = "cocotreb@tpt14g5:~"
dynamic_title = true
opacity = 0.9
dimensions = { columns = 95, lines = 28 }

[font]
normal = {family = "JetBrainsMonoNerdFont"}
size = 14

# XTerm's default colors

# Default colors
[colors.primary]
background = '#0b0b0b'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#cd0000'
green   = '#00cd00'
yellow  = '#cdcd00'
blue    = '#0000ee'
magenta = '#cd00cd'
cyan    = '#00cdcd'
white   = '#e5e5e5'

# Bright colors
[colors.bright]
black   = '#7f7f7f'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#5c5cff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#ffffff'
